from typing import TypedDict, Literal, Optional



class _Literal:
    def __getitem__(self, items):
        class _LiteralClassType():
            base_type = items
            def __getitem__(self, items):
                class _LiteralClass(self.base_type):
                    allowed_values = items
                    def __init__(self, value: self.base_type):
                        if value not in self.allowed_values:
                            raise ValueError(f"{value!r} is not in {self.allowed_values}")
                        super().__init__()
                return _LiteralClass
        return _LiteralClassType()
LiteralTag = _Literal()


minecraft_tag_list = [
    "acacia_logs",
    "anvil",
    "armadillo_food",
    "arrows",
    "axes",
    "axolotl_food",
    "bamboo_blocks",
    "banners",
    "beacon_payment_items",
    "beds",
    "bee_food",
    "birch_logs",
    "boats",
    "bookshelf_books",
    "breaks_decorated_pots",
    "buttons",
    "camel_food",
    "candles",
    "cat_food",
    "cherry_logs",
    "chest_armor",
    "chest_boats",
    "chicken_food",
    "cluster_max_harvestables",
    "coal_ores",
    "coals",
    "compasses",
    "completes_find_tree_tutorial",
    "copper_ores",
    "cow_food",
    "creeper_drop_music_discs",
    "creeper_igniters",
    "crimson_stems",
    "dampens_vibrations",
    "dark_oak_logs",
    "decorated_pot_ingredients",
    "decorated_pot_sherds",
    "diamond_ores",
    "dirt",
    "doors",
    "dyeable",
    "emerald_ores",
    "enchantable/armor",
    "enchantable/bow",
    "enchantable/chest_armor",
    "enchantable/crossbow",
    "enchantable/durability",
    "enchantable/equippable",
    "enchantable/fire_aspect",
    "enchantable/fishing",
    "enchantable/foot_armor",
    "enchantable/head_armor",
    "enchantable/leg_armor",
    "enchantable/mace",
    "enchantable/mining",
    "enchantable/mining_loot",
    "enchantable/sharp_weapon",
    "enchantable/sword",
    "enchantable/trident",
    "enchantable/vanishing",
    "enchantable/weapon",
    "fence_gates",
    "fences",
    "fishes",
    "flowers",
    "foot_armor",
    "fox_food",
    "freeze_immune_wearables",
    "frog_food",
    "goat_food",
    "gold_ores",
    "hanging_signs",
    "head_armor",
    "hoes",
    "hoglin_food",
    "horse_food",
    "horse_tempt_items",
    "ignored_by_piglin_babies",
    "iron_ores",
    "jungle_logs",
    "lapis_ores",
    "leaves",
    "lectern_books",
    "leg_armor",
    "llama_food",
    "llama_tempt_items",
    "logs",
    "logs_that_burn",
    "mangrove_logs",
    "meat",
    "non_flammable_wood",
    "noteblock_top_instruments",
    "oak_logs",
    "ocelot_food",
    "panda_food",
    "parrot_food",
    "parrot_poisonous_food",
    "pickaxes",
    "pig_food",
    "piglin_food",
    "piglin_loved",
    "piglin_repellents",
    "planks",
    "rabbit_food",
    "rails",
    "redstone_ores",
    "sand",
    "saplings",
    "sheep_food",
    "shovels",
    "signs",
    "skulls",
    "slabs",
    "small_flowers",
    "smelts_to_glass",
    "sniffer_food",
    "soul_fire_base_blocks",
    "spruce_logs",
    "stairs",
    "stone_bricks",
    "stone_buttons",
    "stone_crafting_materials",
    "stone_tool_materials",
    "strider_food",
    "strider_tempt_items",
    "swords",
    "tall_flowers",
    "terracotta",
    "trapdoors",
    "trim_materials",
    "trim_templates",
    "trimmable_armor",
    "turtle_food",
    "villager_plantable_seeds",
    "walls",
    "warped_stems",
    "wart_blocks",
    "wolf_food",
    "wooden_buttons",
    "wooden_doors",
    "wooden_fences",
    "wooden_pressure_plates",
    "wooden_slabs",
    "wooden_stairs",
    "wooden_trapdoors",
    "wool",
    "wool_carpets"
]

minecraft_tag_dict = TypedDict("minecraft_tag_dict", {
    "acacia_logs": Optional[Literal[1]],
    "anvil": Optional[Literal[1]],
    "armadillo_food": Optional[Literal[1]],
    "arrows": Optional[Literal[1]],
    "axes": Optional[Literal[1]],
    "axolotl_food": Optional[Literal[1]],
    "bamboo_blocks": Optional[Literal[1]],
    "banners": Optional[Literal[1]],
    "beacon_payment_items": Optional[Literal[1]],
    "beds": Optional[Literal[1]],
    "bee_food": Optional[Literal[1]],
    "birch_logs": Optional[Literal[1]],
    "boats": Optional[Literal[1]],
    "bookshelf_books": Optional[Literal[1]],
    "breaks_decorated_pots": Optional[Literal[1]],
    "buttons": Optional[Literal[1]],
    "camel_food": Optional[Literal[1]],
    "candles": Optional[Literal[1]],
    "cat_food": Optional[Literal[1]],
    "cherry_logs": Optional[Literal[1]],
    "chest_armor": Optional[Literal[1]],
    "chest_boats": Optional[Literal[1]],
    "chicken_food": Optional[Literal[1]],
    "cluster_max_harvestables": Optional[Literal[1]],
    "coal_ores": Optional[Literal[1]],
    "coals": Optional[Literal[1]],
    "compasses": Optional[Literal[1]],
    "completes_find_tree_tutorial": Optional[Literal[1]],
    "copper_ores": Optional[Literal[1]],
    "cow_food": Optional[Literal[1]],
    "creeper_drop_music_discs": Optional[Literal[1]],
    "creeper_igniters": Optional[Literal[1]],
    "crimson_stems": Optional[Literal[1]],
    "dampens_vibrations": Optional[Literal[1]],
    "dark_oak_logs": Optional[Literal[1]],
    "decorated_pot_ingredients": Optional[Literal[1]],
    "decorated_pot_sherds": Optional[Literal[1]],
    "diamond_ores": Optional[Literal[1]],
    "dirt": Optional[Literal[1]],
    "doors": Optional[Literal[1]],
    "dyeable": Optional[Literal[1]],
    "emerald_ores": Optional[Literal[1]],
    "enchantable/armor": Optional[Literal[1]],
    "enchantable/bow": Optional[Literal[1]],
    "enchantable/chest_armor": Optional[Literal[1]],
    "enchantable/crossbow": Optional[Literal[1]],
    "enchantable/durability": Optional[Literal[1]],
    "enchantable/equippable": Optional[Literal[1]],
    "enchantable/fire_aspect": Optional[Literal[1]],
    "enchantable/fishing": Optional[Literal[1]],
    "enchantable/foot_armor": Optional[Literal[1]],
    "enchantable/head_armor": Optional[Literal[1]],
    "enchantable/leg_armor": Optional[Literal[1]],
    "enchantable/mace": Optional[Literal[1]],
    "enchantable/mining": Optional[Literal[1]],
    "enchantable/mining_loot": Optional[Literal[1]],
    "enchantable/sharp_weapon": Optional[Literal[1]],
    "enchantable/sword": Optional[Literal[1]],
    "enchantable/trident": Optional[Literal[1]],
    "enchantable/vanishing": Optional[Literal[1]],
    "enchantable/weapon": Optional[Literal[1]],
    "fence_gates": Optional[Literal[1]],
    "fences": Optional[Literal[1]],
    "fishes": Optional[Literal[1]],
    "flowers": Optional[Literal[1]],
    "foot_armor": Optional[Literal[1]],
    "fox_food": Optional[Literal[1]],
    "freeze_immune_wearables": Optional[Literal[1]],
    "frog_food": Optional[Literal[1]],
    "goat_food": Optional[Literal[1]],
    "gold_ores": Optional[Literal[1]],
    "hanging_signs": Optional[Literal[1]],
    "head_armor": Optional[Literal[1]],
    "hoes": Optional[Literal[1]],
    "hoglin_food": Optional[Literal[1]],
    "horse_food": Optional[Literal[1]],
    "horse_tempt_items": Optional[Literal[1]],
    "ignored_by_piglin_babies": Optional[Literal[1]],
    "iron_ores": Optional[Literal[1]],
    "jungle_logs": Optional[Literal[1]],
    "lapis_ores": Optional[Literal[1]],
    "leaves": Optional[Literal[1]],
    "lectern_books": Optional[Literal[1]],
    "leg_armor": Optional[Literal[1]],
    "llama_food": Optional[Literal[1]],
    "llama_tempt_items": Optional[Literal[1]],
    "logs": Optional[Literal[1]],
    "logs_that_burn": Optional[Literal[1]],
    "mangrove_logs": Optional[Literal[1]],
    "meat": Optional[Literal[1]],
    "non_flammable_wood": Optional[Literal[1]],
    "noteblock_top_instruments": Optional[Literal[1]],
    "oak_logs": Optional[Literal[1]],
    "ocelot_food": Optional[Literal[1]],
    "panda_food": Optional[Literal[1]],
    "parrot_food": Optional[Literal[1]],
    "parrot_poisonous_food": Optional[Literal[1]],
    "pickaxes": Optional[Literal[1]],
    "pig_food": Optional[Literal[1]],
    "piglin_food": Optional[Literal[1]],
    "piglin_loved": Optional[Literal[1]],
    "piglin_repellents": Optional[Literal[1]],
    "planks": Optional[Literal[1]],
    "rabbit_food": Optional[Literal[1]],
    "rails": Optional[Literal[1]],
    "redstone_ores": Optional[Literal[1]],
    "sand": Optional[Literal[1]],
    "saplings": Optional[Literal[1]],
    "sheep_food": Optional[Literal[1]],
    "shovels": Optional[Literal[1]],
    "signs": Optional[Literal[1]],
    "skulls": Optional[Literal[1]],
    "slabs": Optional[Literal[1]],
    "small_flowers": Optional[Literal[1]],
    "smelts_to_glass": Optional[Literal[1]],
    "sniffer_food": Optional[Literal[1]],
    "soul_fire_base_blocks": Optional[Literal[1]],
    "spruce_logs": Optional[Literal[1]],
    "stairs": Optional[Literal[1]],
    "stone_bricks": Optional[Literal[1]],
    "stone_buttons": Optional[Literal[1]],
    "stone_crafting_materials": Optional[Literal[1]],
    "stone_tool_materials": Optional[Literal[1]],
    "strider_food": Optional[Literal[1]],
    "strider_tempt_items": Optional[Literal[1]],
    "swords": Optional[Literal[1]],
    "tall_flowers": Optional[Literal[1]],
    "terracotta": Optional[Literal[1]],
    "trapdoors": Optional[Literal[1]],
    "trim_materials": Optional[Literal[1]],
    "trim_templates": Optional[Literal[1]],
    "trimmable_armor": Optional[Literal[1]],
    "turtle_food": Optional[Literal[1]],
    "villager_plantable_seeds": Optional[Literal[1]],
    "walls": Optional[Literal[1]],
    "warped_stems": Optional[Literal[1]],
    "wart_blocks": Optional[Literal[1]],
    "wolf_food": Optional[Literal[1]],
    "wooden_buttons": Optional[Literal[1]],
    "wooden_doors": Optional[Literal[1]],
    "wooden_fences": Optional[Literal[1]],
    "wooden_pressure_plates": Optional[Literal[1]],
    "wooden_slabs": Optional[Literal[1]],
    "wooden_stairs": Optional[Literal[1]],
    "wooden_trapdoors": Optional[Literal[1]],
    "wool": Optional[Literal[1]],
    "wool_carpets": Optional[Literal[1]],
})