name: Update the documentation
on:
  workflow_dispatch:
  # only run on master branch on push that modifies data/ by edayot
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'README.md'
      - 'CHANGELOG.md'
  release:
    types: [published]



jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.14
        uses: actions/setup-python@v2
        with:
          python-version: 3.14
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --group dev


      - name: Sphinx build
        run: |
          cd docs/
          uv run sphinx-build . _build
          cd ../
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
          tag_message: 'Deployment ${{ github.ref_name }}'
          destination_dir: "."

      
      
